### ISSUE TITLE
Error displaying category page in Magento Cloud

### ISSUE THREAD

**Issue by kevincarcache-omni** [Simicart/siminia-public#333]
# 🐞 Report

### Description

When we deploy siminia to Magento Cloud, there is an error displayed in the console when we try to enter to the category page and the after that the page continuosly refresh 
### 🔬 Minimal Reproduction

- deploy the magento cloud environment
- in the magento cloud build hook there is a script that excecute yarn install and yarn build
- CONFIG__DEFAULT__WEB__UPWARD__PATH=/app/<proyect_id>/pwa/upward.yml
- We go to the deployed website
- Enter in the category page

### Exception/Error message

<pre><code>
Sorry! An unexpected error occurred. Debug: TypeError114 at useAddToListButton (/client.24a293eaf8c15356c960.js:951:170)

TypeError: Cannot read properties of undefined (reading 'enable_multiple_wishlists')
    at useAddToListButton (https://mcstaging.sawyersfresh.com/client.24a293eaf8c15356c960.js:951:170)
    at AddToListButton (https://mcstaging.sawyersfresh.com/client.24a293eaf8c15356c960.js:982:546)
    at Ch (https://&lt;magentosite&gt;/runtime.b7f06d060cc7f785064e.js:1523:150)
    at va (https://&lt;magentosite&gt;/runtime.b7f06d060cc7f785064e.js:2152:147)
    at bk (https://&lt;magentosite&gt;/runtime.b7f06d060cc7f785064e.js:1996:126)
    at ak (https://&lt;magentosite&gt;/runtime.b7f06d060cc7f785064e.js:1996:54)
    at Tj (https://&lt;magentosite&gt;/runtime.b7f06d060cc7f785064e.js:1994:35)
    at Lj (https://&lt;magentosite&gt;/runtime.b7f06d060cc7f785064e.js:1939:40)
    at https://&lt;magentosite&gt;/runtime.b7f06d060cc7f785064e.js:1391:6
    at t.unstable_runWithPriority (https://&lt;magentosite&gt;/client.24a293eaf8c15356c960.js:2311:12)
</code></pre>

### Your environment

Magento Cloud (Linux)

### Expected behaviour

The website shows category products like the demo page https://magento.pwa-commerce.com/women/tops-women/jackets-women.html

### Possible solution

We thing that it has something to do with the upward.yml configuration

**Comment by codynguyen1** [comment]
Hi @kevincarcache-omni , it seem to be the Magento version you are using has no multiple wishlist feature (which is only on Enterprise edition), please update your .env file and run it again.
